### PR TITLE
LRQA-57574 Adding new OAuth2 test case with SAML login flow

### PR DESCRIPTION
**Pull request by weller0246**
https://issues.liferay.com/browse/LRQA-57574

### CODE REVIEW

**Comment by weller0246** [comment]
ci:test:sf

**Comment by weller0246** [comment]
ci:test:security:nocompile

**Comment by weller0246** [comment]
ci:test:security:nocompile

**Comment by weller0246** [comment]
ci:test:security:nocompile

**Comment by weller0246** [comment]
ci:test:security:nocompile

**Comment by weller0246** [comment]
ci:test:security:nocompile

**Review by gaborlovasdotcom — CHANGES_REQUESTED** [review]
Please send it to review only, when it passes at CI.
According to the current status at CI, it's still in progress.

**Comment by weller0246** [comment]
ci:test:security:nocompile

**Comment by gaborlovasdotcom** [comment]
ci:test:sf

**Comment by weller0246** [comment]
@gaborlovasdotcom  @ferenconodiD  please review the code if you have the time, thank you.
The tests are in quarantine as  [LPS-137257](https://issues.liferay.com/browse/LPS-137257?jql=project%20in%20(LPS%2C%20LRHU%2C%20LRQA%2C%20BPR)%20AND%20resolution%20%3D%20Unresolved%20AND%20assignee%20in%20(currentUser())) needs to be fixed in order for the function to work properly

**Comment by gaborlovasdotcom** [comment]
ci:test:oauth2:nocompile

**Comment by gaborlovasdotcom** [comment]
@weller0246 I fixed some typos in the test code, looks ok now.

**Comment by gaborlovasdotcom** [comment]
ci:test:sf

**Review by gaborlovasdotcom — APPROVED** [review]

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Pull request closed without merging**
