### PR TITLE
LRQA-72513 | master

### PR DESCRIPTION
**Pull request by JoyceWang08211**
https://issues.liferay.com/browse/LRQA-72513

### CODE REVIEW

**Comment by JoyceWang08211** [comment]
ci:test:sf

**Review by gaborlovasdotcom — APPROVED** [review]

**Comment by gaborlovasdotcom** [comment]
@JoyceWang08211 Could you please resolve the conflict in the Login.testcase?

**Comment by JoyceWang08211** [comment]
ci:test:sf

**Comment by JoyceWang08211** [comment]
> @JoyceWang08211 Could you please resolve the conflict in the Login.testcase?

Done

**Comment by gaborlovasdotcom** [comment]
ci:test:security:nocompile

**Review by gaborlovasdotcom — APPROVED** [review]

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Comment by gaborlovasdotcom** [comment]
ci:test:relevant

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Pull request closed without merging**
