### PR TITLE
LRQA-70437, LRQA-70442 | master

### PR DESCRIPTION
**Pull request by Kvale1733**
https://issues.liferay.com/browse/LRQA-70437
https://issues.liferay.com/browse/LRQA-70442

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
ci:test:security:nocompile

**Review by gaborlovasdotcom — APPROVED** [review]
LGTM,
Test run errors are the same as in [recent](https://testray.liferay.com/home/-/testray/case_results/index?p_p_state=normal&orderByCol=status_sortable&orderByType=asc&testrayBuildId=1581933150&testrayComponentId=1310779464&statuses=3) master daily

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Pull request closed without merging**
