### PR TITLE
LPS-131057 Specify 32GB environment for test case

### PR DESCRIPTION
**Pull request by gaborlovasdotcom**
https://issues.liferay.com/browse/LPS-131057

Continued from: https://github.com/gaborlovasdotcom/liferay-portal/pull/78

cc: @JoyceWang08211

### CODE REVIEW

**Comment by gaborlovasdotcom** [comment]
ci:test:oauth2:nocompile

**Comment by gaborlovasdotcom** [comment]
ci:test:sf

**Comment by gaborlovasdotcom** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
ci:test:oauth2 (rerunning this test because the previous one has already been purged by Jenkins)

**Comment by gaborlovasdotcom** [comment]
ci:help

**Comment by gaborlovasdotcom** [comment]
ci:test:oauth2

**Comment by gaborlovasdotcom** [comment]
ci:test:oauth2

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Pull request closed without merging**
