### PR TITLE
LPS-132754 Test SAMLUpgrades at DB2 database only

### PR DESCRIPTION
**Pull request by gaborlovasdotcom**
https://issues.liferay.com/browse/LPS-132754

cc: @martamedio

### CODE REVIEW

**Comment by gaborlovasdotcom** [comment]
ci:test:sf

**Comment by gaborlovasdotcom** [comment]
ci:test:security:nocompile

**Comment by gaborlovasdotcom** [comment]
ci:stop

**Comment by gaborlovasdotcom** [comment]
ci:test:security

**Comment by JoyceWang08211** [comment]
ci:test:security

**Comment by gaborlovasdotcom** [comment]
Testing is continued with developer fix in https://github.com/liferay-appsec/liferay-portal/pull/426

**Pull request closed without merging**
