### PR TITLE
LRQA-70641 Fixing menu item name for OpenID Connect

### PR DESCRIPTION
**Pull request by ferenconodiD**
[LRQA-70641](https://issues.liferay.com/browse/LRQA-70641)

### CODE REVIEW

**Comment by ferenconodiD** [comment]
ci:test:sf

**Comment by ferenconodiD** [comment]
ci:test:login:nocompile

**Comment by ferenconodiD** [comment]
ci:test:security:nocompile

**Comment by ferenconodiD** [comment]
ci:test:security:nocompile

**Review by gaborlovasdotcom — APPROVED** [review]
LGTM!

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Pull request closed without merging**
