### PR TITLE
LRQA-71063

### PR DESCRIPTION
**Pull request by 91nilo**
https://issues.liferay.com/browse/LRQA-71063

### CODE REVIEW

**Comment by 91nilo** [comment]
ci:test:staging

**Review by gaborlovasdotcom — CHANGES_REQUESTED** [review]
Hi @91nilo,
Could you please add ticket IDs as prefixes for the descriptions too?
We used to check the test case's git history and review which Jira ticket added the test case first. It used to be either a bug ticket or a user story.
Also, feel free to add a "dot" to the end of the descriptions text.
We also used to soften the sentence by replacing the word "Assert" with "Verify that... XY could happen." This way the description sounds more Business focused, and less technical.
You could check this PR about what I'm thinking, where @Kvale1733 also updated a few AppSec test case descriptions: https://github.com/gaborlovasdotcom/liferay-portal/pull/196#pullrequestreview-797583422.

cc: @JoyceWang08211 , @weller0246

**Comment by 91nilo** [comment]
ci:test:sf

**Comment by 91nilo** [comment]
Sent on https://github.com/gaborlovasdotcom/liferay-portal/pull/341
Closing this one.

**Pull request closed without merging**
