### PR TITLE
LRQA-71436, LRQA-71438, LRQA-71433, LRQA-71442, LRQA-71441, LRQA-71437 | master

### PR DESCRIPTION
**Pull request by Kvale1733**
https://issues.liferay.com/browse/LRQA-71436
https://issues.liferay.com/browse/LRQA-71438
https://issues.liferay.com/browse/LRQA-71433
https://issues.liferay.com/browse/LRQA-71442
https://issues.liferay.com/browse/LRQA-71441
https://issues.liferay.com/browse/LRQA-71437

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
ci:test:security:nocompile

**Review by weller0246 — APPROVED** [review]
Nice optimization!

**Review by gaborlovasdotcom — APPROVED** [review]
Nice work!

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Pull request closed without merging**
