### PR TITLE
LRQA-70542 | master

### PR DESCRIPTION
**Pull request by Kvale1733**
https://issues.liferay.com/browse/LRQA-70542

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:sf

**Review by ferenconodiD — APPROVED** [review]
LGTM!

@Kvale1733 Though this is a minor change, in the future please execute a job where the affected tests can run.

**Comment by gaborlovasdotcom** [comment]
ci:test:security:nocompile

**Review by gaborlovasdotcom — APPROVED** [review]

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Pull request closed without merging**
