### PR TITLE
LPS-132629 Update Login.testcase to use UI login flow

### PR DESCRIPTION
**Pull request by gaborlovasdotcom**
https://issues.liferay.com/browse/LPS-132629

### CODE REVIEW

**Comment by gaborlovasdotcom** [comment]
ci:test:security:nocompile

**Comment by JoyceWang08211** [comment]
Suggestion:
1. For commit message, we don't need to write out the specific test case name. Since these two commits are doing the same thing, we can combine them as one commit with the following message: 
`LPS-132629 Update test to use UI login step`
2.  You may need to double check **LocalFile.Login#TokenBasedSSOSmoke** and **LocalFile.Login#FacebookSSOSmoke**. They are failed on ci:test:security with the fix.

**Comment by gaborlovasdotcom** [comment]
Fixes applied, re-run tests.

**Comment by gaborlovasdotcom** [comment]
ci:test:security:nocompile

**Comment by gaborlovasdotcom** [comment]
ci:test:security:nocompile

**Comment by JoyceWang08211** [comment]
Need to update the usage of **_PortalSettings.gotoConfiguration_** in Login.testcase when configure settings on instance. Please refer to the following:
https://github.com/liferay/liferay-portal/blob/master/portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructureee/security/mfa/MultiFactorAuthentication.testcase#L84

**Comment by gaborlovasdotcom** [comment]
ci:test:security:nocompile

**Comment by gaborlovasdotcom** [comment]
ci:test:security:nocompile

**Comment by gaborlovasdotcom** [comment]
ci:test:security:nocompile

**Comment by gaborlovasdotcom** [comment]
ci:test:sf

**Comment by gaborlovasdotcom** [comment]
ci:test:security:nocompile

**Comment by gaborlovasdotcom** [comment]
Continued in https://github.com/gaborlovasdotcom/liferay-portal/pull/85

**Pull request closed without merging**
