### PR TITLE
LRQA-71127 Add description to test cases

### PR DESCRIPTION
**Pull request by weller0246**
https://issues.liferay.com/browse/LRQA-71127

### CODE REVIEW

**Comment by weller0246** [comment]
Please review my PR if you have the time!

**Review by gaborlovasdotcom — APPROVED** [review]
LGTM
@JoyceWang08211 Feel free to forward when your review is done

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Pull request closed without merging**
