### PR TITLE
LPS-148309

### PR DESCRIPTION
**Pull request by weller0246**
https://issues.liferay.com/browse/LPS-148309

### CODE REVIEW

**Comment by weller0246** [comment]
ci:test:sf

**Comment by weller0246** [comment]
ci:test:staging:nocompile

**Comment by gaborlovasdotcom** [comment]
ci:stop

**Comment by gaborlovasdotcom** [comment]
@weller0246 , Please don't start CI test run, when SF job is not completes.

**Comment by weller0246** [comment]
ci:test:sf

**Comment by weller0246** [comment]
ci:test:staging:nocompile

**Comment by weller0246** [comment]
ci:test:staging:nocompile

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Review by gaborlovasdotcom — APPROVED** [review]
LGTM

**Pull request closed without merging**
