### PR TITLE
LPS-135788 Extend clickSignInLink macro parameters to be able to handle multiple IdP portals

### PR DESCRIPTION
**Pull request by weller0246**
https://issues.liferay.com/browse/LPS-135788

### CODE REVIEW

**Comment by weller0246** [comment]
ci:test:sf

**Comment by weller0246** [comment]
ci:test:security

**Comment by weller0246** [comment]
ci:test:staging

**Comment by gaborlovasdotcom** [comment]
Fix already merged into file: https://github.com/liferay/liferay-portal/blob/master/portal-web/test/functional/com/liferay/portalweb/macros/User.macro#L1955

**Pull request closed without merging**
