### PR TITLE
LRQA-70438, LRQA-70432 | master

### PR DESCRIPTION
**Pull request by Kvale1733**
https://issues.liferay.com/browse/LRQA-70438
https://issues.liferay.com/browse/LRQA-70432

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
ci:test:security:nocompile

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
ci:test:saml:nocompile

**Review by gaborlovasdotcom — CHANGES_REQUESTED** [review]
Hi @Kvale1733, in the SAML test cases, the additional instances are using "liferay.com" as their domain (aka email domain), the current SAML macros are prepared to use this email address domain most of the time.
Could you please change them to use liferay.com for www.able.com and www.baker.com, and re-run the tests?

**Comment by Kvale1733** [comment]
@gaborlovasdotcom Can you point out a macro specifically? I just looked through the testcase. I thought you were referring to the SAML.addVirtualInstances macro but I looked through the runs on testray and none of those seem to use liferay.com as email domain.

**Comment by gaborlovasdotcom** [comment]
ci:test:sf

**Comment by gaborlovasdotcom** [comment]
ci:test:saml:nocompile

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
ci:test:saml:nocompile

**Comment by Kvale1733** [comment]
ci:test:saml:nocompile

**Comment by Kvale1733** [comment]
ci:stop

**Comment by Kvale1733** [comment]
It looks like the HeadlessPortalInstanceAPI.addPortalInstance() macro is failing to even add the virtual instances and so the tests fail.

**Comment by Kvale1733** [comment]
ci:stop

**Comment by Kvale1733** [comment]
Upon inspection, it looks like the API now requires siteInitializerKey and companyId values to be set in the curl. The macro currently does not set these values. Setting them fixes the macro.

**Review by gaborlovasdotcom — APPROVED** [review]

**Comment by gaborlovasdotcom** [comment]
ci:test:saml:nocompile

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Pull request closed without merging**
