### PR TITLE
LPS-133093 Adding new SAML test cases

### PR DESCRIPTION
**Pull request by weller0246**
https://issues.liferay.com/browse/LPS-133093

### CODE REVIEW

**Comment by weller0246** [comment]
ci:test:sf

**Comment by weller0246** [comment]
ci:test:saml:nocompile

**Comment by weller0246** [comment]
ci:test:saml:nocompile

**Review by gaborlovasdotcom — CHANGES_REQUESTED** [review]
Please use meaningful commit messages even for smaller changes, to keep commit history meaningful for others.

Also, tests should pass at CI too before we forward them.

cc @JoyceWang08211 @ferenconodiD

**Comment by gaborlovasdotcom** [comment]
ci:test:saml:nocompile

**Comment by weller0246** [comment]
ci:test:saml:nocompile

**Comment by gaborlovasdotcom** [comment]
Fixes are applied and rebased in https://github.com/gaborlovasdotcom/liferay-portal/pull/125
final version sent from https://github.com/gaborlovasdotcom/liferay-portal/pull/125
to BChan in https://github.com/brianchandotcom/liferay-portal/pull/104823

CC: @weller0246

**Pull request closed without merging**
