### PR TITLE
LRQA-66199 Add new test cases for Revoke Authorization button in OAuth2 Administration page

### PR DESCRIPTION
**Pull request by weller0246**
https://issues.liferay.com/browse/LRQA-66199

### CODE REVIEW

**Comment by weller0246** [comment]
ci:test:oauth2:nocompile

**Comment by weller0246** [comment]
ci:test:oauth2

**Comment by weller0246** [comment]
ć

**Comment by weller0246** [comment]
ci:test:oauth2:nocompile

**Comment by weller0246** [comment]
ci:test:oauth2:nocompile

**Review by gaborlovasdotcom — CHANGES_REQUESTED** [review]
Please fix the test cases to pass at CI, to start the review.
Don't forget to mention the ticket ID to the name of your commits.

cc @JoyceWang08211

**Comment by weller0246** [comment]
ci:test:oauth2:nocompile

**Review by gaborlovasdotcom — APPROVED** [review]

**Review by gaborlovasdotcom — APPROVED** [review]
LGTM

**Comment by gaborlovasdotcom** [comment]
ci:test:sf

**Comment by gaborlovasdotcom** [comment]
ci:test:oauth2:nocompile

**Comment by weller0246** [comment]
ci:test:sf

**Comment by gaborlovasdotcom** [comment]
ci:test:oauth2:nocompile

**Review by gaborlovasdotcom — APPROVED** [review]

**Comment by gaborlovasdotcom** [comment]
ci:test:oauth2:nocompile

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Pull request closed without merging**
