### PR TITLE
Group id test

### PR DESCRIPTION
**Pull request by gaborlovasdotcom**

### CODE REVIEW

**Comment by gaborlovasdotcom** [comment]
ci:test:sf

**Comment by gaborlovasdotcom** [comment]
ci:test:sf

**Comment by JoyceWang08211** [comment]
It might be due to these config files haven't deployed in portal yet. 
You could set a 3000 pause before CookieNavigator.gotoSiteSettings(portlet = "Banner"); to have a try.

**Comment by gaborlovasdotcom** [comment]
ci:test:security:nocompile

**Comment by gaborlovasdotcom** [comment]
ci:test:security:nocompile

**Comment by gaborlovasdotcom** [comment]
Continued in https://github.com/gaborlovasdotcom/liferay-portal/pull/404

**Pull request closed without merging**
