### PR TITLE
LRQA-74016 | master

### PR DESCRIPTION
**Pull request by weller0246**
https://issues.liferay.com/browse/LRQA-74016

### CODE REVIEW

**Comment by gaborlovasdotcom** [comment]
ci:test:sf

**Comment by gaborlovasdotcom** [comment]
ci:test:staging:nocompile

**Review by gaborlovasdotcom — APPROVED** [review]

**Comment by weller0246** [comment]
ci:test:bundle:norebase

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Comment by gaborlovasdotcom** [comment]
> ci:test:bundle:norebase

@weller0246, as this PR contains only is test code changes, no need for the :rebase option

**Pull request closed without merging**
