### PR TITLE
LPS-138634 Add Staging post-upgrade tests

### PR DESCRIPTION
**Pull request by ferenconodiD**
[LPS-138634](https://issues.liferay.com/browse/LPS-138634)

### CODE REVIEW

**Comment by ferenconodiD** [comment]
ci:test:staging

**Comment by ferenconodiD** [comment]
ci:test:staging:nocompile

**Comment by ferenconodiD** [comment]
ci:test:sf

**Review by JoyceWang08211 — COMMENTED** [review]
1. DefaultSiteCanBeExportedAfterUpgradeXXX - LGTM.

2. ExportTemplateCanBeEditedAfterUpgradeXXX - Miss the last step **"Assert export template is updated as expected"**.
Suggest to execute an export process by using this export template and import the site lar to a new site. Assert only blog content displays in the new site and no web content display in the new site. Then we can ensure the edited template works well after upgraded.

**Review by gaborlovasdotcom — CHANGES_REQUESTED** [review]
Looks good, but we need the changes @JoyceWang08211 mentioned.

**Comment by ferenconodiD** [comment]
ci:test:sf

**Comment by ferenconodiD** [comment]
ci:test:staging:nocompile

**Comment by ferenconodiD** [comment]
ci:test:staging:nocompile

**Comment by JoyceWang08211** [comment]
ci:test:staging:nocompile

**Review by JoyceWang08211 — APPROVED** [review]
LGTM!

**Review by gaborlovasdotcom — APPROVED** [review]

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Pull request closed without merging**
