### PR TITLE
LRQA-70493, LRQA-70494, LRQA-70498 | master

### PR DESCRIPTION
**Pull request by Kvale1733**
https://issues.liferay.com/browse/LRQA-70493
https://issues.liferay.com/browse/LRQA-70494
https://issues.liferay.com/browse/LRQA-70498

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
ci:test:security:nocompile

**Review by gaborlovasdotcom — APPROVED** [review]
LGTM!

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Pull request closed without merging**
