### PR TITLE
LRQA-70565 | OAuth2Upgrade.testcase | SACRED update: Apply task groups on test steps

### PR DESCRIPTION
**Pull request by LucasAcacio**
https://issues.liferay.com/browse/LRQA-70565

### CODE REVIEW

**Comment by LucasAcacio** [comment]
ci:test:sf

**Comment by LucasAcacio** [comment]
ci:test:security

**Review by gaborlovasdotcom — CHANGES_REQUESTED** [review]
Please fix the commit message with proper task id thanks

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Review by gaborlovasdotcom — APPROVED** [review]
LGTM!

**Pull request closed without merging**
