### PR TITLE
LRQA-72186 Set 24GB of RAM for SAML test cases

### PR DESCRIPTION
**Pull request by gaborlovasdotcom**
[LRQA-72186](https://issues.liferay.com/browse/LRQA-72186)

### CODE REVIEW

**Comment by gaborlovasdotcom** [comment]
ci:test:sf

**Comment by gaborlovasdotcom** [comment]
ci:test:saml:nocompile

**Review by ferenconodiD — COMMENTED** [review]
LGTM!

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Pull request closed without merging**
