### PR TITLE
LPS-152452, LPS-152844 dynamic view + tests

### PR DESCRIPTION
**Pull request by gaborlovasdotcom**
[LPS-152452](https://issues.liferay.com/browse/LPS-152452)
[LPS-152844](https://issues.liferay.com/browse/LPS-152844)

### CODE REVIEW

**Comment by gaborlovasdotcom** [comment]
ci:test:cookies

**Comment by gaborlovasdotcom** [comment]
ci:test:sf

**Comment by jkappler** [comment]
Thanks for letting me know @gaborlovasdotcom!

**Comment by gaborlovasdotcom** [comment]
ci:test:cookies

**Comment by jkappler** [comment]
@gaborlovasdotcom, thanks a lot!

**Comment by gaborlovasdotcom** [comment]
ci:test:relevant

**Comment by gaborlovasdotcom** [comment]
Continued in https://github.com/liferay-appsec/liferay-portal/pull/650

**Pull request closed without merging**
