### PR TITLE
LPS-134369 Update test.properties to include Crypto hash related unit and integration tests

### PR DESCRIPTION
**Pull request by gaborlovasdotcom**
https://issues.liferay.com/browse/LPS-134369

cc @JoyceWang08211

### CODE REVIEW

**Comment by gaborlovasdotcom** [comment]
ci:test:sf

**Comment by gaborlovasdotcom** [comment]
ci:test:security:nocompile

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Comment by gaborlovasdotcom** [comment]
ci:test:relevant

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by gaborlovasdotcom** [comment]
ci:test:relevant

**Comment by JoyceWang08211** [comment]
Forward to BChan https://github.com/brianchandotcom/liferay-portal/pull/103738

**Pull request closed without merging**
