### PR TITLE
LRQA-70507, LRQA-70508 | master

### PR DESCRIPTION
**Pull request by Kvale1733**
https://issues.liferay.com/browse/LRQA-70507
https://issues.liferay.com/browse/LRQA-70508

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
ci:test:security:nocompile

**Review by gaborlovasdotcom — APPROVED** [review]

**Comment by gaborlovasdotcom** [comment]
The XSS#NoXSSVulnerabilityInBlogsEntryCustomAbstract will be fixed under [LPS-141209](https://issues.liferay.com/browse/LPS-141209)

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Pull request closed without merging**
