### PR TITLE
LRQA-75802 | master

### PR DESCRIPTION
**Pull request by JingyuanZhao**
https://issues.liferay.com/browse/LRQA-75802
@gaborlovasdotcom

### CODE REVIEW

**Comment by JingyuanZhao** [comment]
ci:test:sf

**Comment by JingyuanZhao** [comment]
ci:test:sf

**Comment by gaborlovasdotcom** [comment]
ci:test:staging:nocompile

**Review by gaborlovasdotcom — APPROVED** [review]

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Pull request closed without merging**
