### PR TITLE
LPS-146522 | master

### PR DESCRIPTION
**Pull request by ferenconodiD**
[LPS-146522](https://issues.liferay.com/browse/LPS-146522)

### CODE REVIEW

**Comment by ferenconodiD** [comment]
ci:test:security:nocompile

**Comment by ferenconodiD** [comment]
ci:test:security:nocompile

**Comment by ferenconodiD** [comment]
ci:test:security:nocompile

**Comment by ferenconodiD** [comment]
ci:test:security:nocompile

**Comment by ferenconodiD** [comment]
ci:test:security:nocompile

**Comment by ferenconodiD** [comment]
ci:test:security:nocompile

**Review by gaborlovasdotcom — APPROVED** [review]
LGTM, remove CI only when it's ready

**Comment by ferenconodiD** [comment]
ci:test:security:nocompile

**Comment by ferenconodiD** [comment]
ci:test:security:nocompile

**Comment by ferenconodiD** [comment]
ci:test:security:nocompile

**Comment by ferenconodiD** [comment]
ci:test:security:nocompile

**Comment by ferenconodiD** [comment]
ci:test:security:nocompile

**Comment by michaelhashimoto** [comment]
ci:stop

**Comment by michaelhashimoto** [comment]
ci:test:security:nocompile

**Comment by ferenconodiD** [comment]
ci:test:security:nocompile

**Review by gaborlovasdotcom — APPROVED** [review]
It seems https working

**Comment by ferenconodiD** [comment]
ci:test:security:nocompile

**Comment by ferenconodiD** [comment]
ci:stop

**Comment by ferenconodiD** [comment]
ci:stop

**Comment by ferenconodiD** [comment]
ci:test:security:nocompile

**Comment by ferenconodiD** [comment]
ci:test:sf

**Review by gaborlovasdotcom — APPROVED** [review]

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Comment by gaborlovasdotcom** [comment]
@ferenconodiD, rebase needed

**Comment by gaborlovasdotcom** [comment]
ci:test:sf

**Comment by gaborlovasdotcom** [comment]
ci:test:oidc:nocompile

**Comment by gaborlovasdotcom** [comment]
ci:test:oidc:nocompile

**Comment by gaborlovasdotcom** [comment]
ci:test:sf

**Comment by gaborlovasdotcom** [comment]
ci:test:oidc:nocompile

**Review by gaborlovasdotcom — APPROVED** [review]

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Pull request closed without merging**
