### PR TITLE
LRQA-70526 | master

### PR DESCRIPTION
**Pull request by Kvale1733**
https://issues.liferay.com/browse/LRQA-70526

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
ci:stop

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
ci:test:security:nocompile

**Review by gaborlovasdotcom — APPROVED** [review]
LGTM, test passed

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Pull request closed without merging**
