### PR TITLE
LRQA-70559 | CORSUpgrade.testcase | SACRED update: Apply task groups on test steps

### PR DESCRIPTION
**Pull request by LucasAcacio**
https://issues.liferay.com/browse/LRQA-70559

### CODE REVIEW

**Comment by LucasAcacio** [comment]
ci:test:sf

**Comment by LucasAcacio** [comment]
ci:test:sf

**Comment by LucasAcacio** [comment]
ci:test:security

**Review by gaborlovasdotcom — CHANGES_REQUESTED** [review]
Please fix the commit's prefix to 70559

**Comment by LucasAcacio** [comment]
ci:test:sf

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Pull request closed without merging**
