### PR TITLE
LRQA-70386 | master

### PR DESCRIPTION
**Pull request by Kvale1733**
https://issues.liferay.com/browse/LRQA-70386

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by nikki-pru** [comment]
It looks like SF passed on this one but Jenkins errored out in adding the github comment. 
```
The following error occurred while executing this line:
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common.xml:9285: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-github.xml:329: Sourced file: inline evaluation of: `` 				 					import com.liferay.jenkins.results.parser.PullRequest; 					import co . . . '' : TargetError : at Line: 21 : in file: inline evaluation of: `` 				 					import com.liferay.jenkins.results.parser.PullRequest; 					import co . . . '' : throw new RuntimeException ( "Unable to update comment" , e ) ; 
```

https://test-1-10.liferay.com/job/test-portal-source-format/3257/console

**Comment by nikki-pru** [comment]
ci:stop

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
ci:test:security:nocompile

**Review by gaborlovasdotcom — APPROVED** [review]
LGTM, tests are passed!

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Pull request closed without merging**
