### PR TITLE
LRQA-70257 Fixing broken if/else statement

### PR DESCRIPTION
**Pull request by ferenconodiD**
[LRQA-70257](https://issues.liferay.com/browse/LRQA-70257)

### CODE REVIEW

**Comment by ferenconodiD** [comment]
ci:test:sf

**Comment by ferenconodiD** [comment]
ci:test:saml:nocompile

**Review by gaborlovasdotcom — APPROVED** [review]
LGTM!

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Pull request closed without merging**
