### PR TITLE
LPS-141212 | master

### PR DESCRIPTION
**Pull request by weller0246**
https://issues.liferay.com/browse/LPS-141212

### CODE REVIEW

**Comment by weller0246** [comment]
ci:test:sf

**Comment by weller0246** [comment]
ci:test:security:nocompile

**Comment by gaborlovasdotcom** [comment]
@weller0246 This might look like a quick fix, but not the best fix, as we didn't find the original root cause of the problem.
I did some investigation and continued this ticket in https://github.com/gaborlovasdotcom/liferay-portal/pull/303.
As I realized the source of the problem is the fact, we are missing to send the parameters UserID and CompanyID to the macro layer.
This might happen during the SACRED rewrite when these new macros are added.
I added some property validation to the macros to prevent such cases.

cc @JoyceWang08211, @ferenconodiD

**Review by gaborlovasdotcom — COMMENTED** [review]
Continued in https://github.com/gaborlovasdotcom/liferay-portal/pull/303

**Pull request closed without merging**
