### PR TITLE
LPS-135063 audit test

### PR DESCRIPTION
**Pull request by gaborlovasdotcom**
https://issues.liferay.com/browse/LPS-139570
From: https://github.com/liferay-appsec/liferay-portal/commits/LPS-135063-audit-test

@ferenconodiD  Please review it and help forward it when the test passes.

### CODE REVIEW

**Comment by gaborlovasdotcom** [comment]
ci:test:security:nocompile

**Comment by gaborlovasdotcom** [comment]
ci:test:security:nocompile

**Comment by gaborlovasdotcom** [comment]
ci:test:sf

**Comment by gaborlovasdotcom** [comment]
ci:test:security:nocompile

**Review by ferenconodiD — APPROVED** [review]
LGTM!
@gaborlovasdotcom We should include **Audit.testcase** in [LRQA-67999](https://issues.liferay.com/browse/LRQA-67999)

**Comment by gaborlovasdotcom** [comment]
> LGTM! @gaborlovasdotcom We should include **Audit.testcase** in [LRQA-67999](https://issues.liferay.com/browse/LRQA-67999)

Thanks, I added it under [LRQA-71428](https://issues.liferay.com/browse/LRQA-71428)

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Pull request closed without merging**
