### PR TITLE
LRQA-72427 | master

### PR DESCRIPTION
**Pull request by JoyceWang08211**
https://issues.liferay.com/browse/LRQA-72427

master only, thx

### CODE REVIEW

**Comment by JoyceWang08211** [comment]
ci:test:sf

**Review by gaborlovasdotcom — APPROVED** [review]
LGTM!

**Comment by gaborlovasdotcom** [comment]
ci:test:staging:nocompile

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Pull request closed without merging**
