### PR TITLE
LPS-135933 Refactor SAMLPortlet.addIdentityProviderConnection to handle different Attribute mapping in SAML

### PR DESCRIPTION
**Pull request by weller0246**
https://issues.liferay.com/browse/LPS-135933

### CODE REVIEW

**Comment by weller0246** [comment]
ci:test:saml:nocompile

**Review by gaborlovasdotcom — APPROVED** [review]
The new macros will be used for the refactored/new SAML test cases.

**Review by ferenconodiD — APPROVED** [review]
LGTM!

**Comment by gaborlovasdotcom** [comment]
Failed test cases are not related to the new macros as new macros are not used in any test cases yet.

**Comment by gaborlovasdotcom** [comment]
ci:foward

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Comment by gaborlovasdotcom** [comment]
ci:stop

**Comment by gaborlovasdotcom** [comment]
ci:test:relevant

**Comment by gaborlovasdotcom** [comment]
ci:test:stable

**Comment by gaborlovasdotcom** [comment]
ci:test:sf

**Pull request closed without merging**
