### PR TITLE
LPS-135063 Asserting audit information is present and correct after enabling log and X-Request-ID

### PR DESCRIPTION
**Pull request by weller0246**
https://issues.liferay.com/browse/LPS-135063

### CODE REVIEW

**Comment by weller0246** [comment]
ci:test:sf

**Comment by weller0246** [comment]
ci:test:security:nocompile

**Comment by weller0246** [comment]
ci:test:sf

**Comment by weller0246** [comment]
ci:test:security:nocompile

**Review by gaborlovasdotcom — APPROVED** [review]
LGTM!

**Comment by gaborlovasdotcom** [comment]
ci:test:security:nocompile

**Review by ferenconodiD — APPROVED** [review]
LGTM!

**Pull request closed without merging**
