### PR TITLE
LRQA-72589 | master

### PR DESCRIPTION
**Pull request by gaborlovasdotcom**
[LRQA-72589](https://issues.liferay.com/browse/LRQA-72589)

Removing test case from environment.acceptance test suite until fixing.

cc  @vicnate5

### CODE REVIEW

**Comment by gaborlovasdotcom** [comment]
ci:test:sf

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Comment by gaborlovasdotcom** [comment]
@vicnate5 Could you please check the PR forwarding error?

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Comment by vicnate5** [comment]
@gaborlovasdotcom you will need to ask CI team.

**Comment by vicnate5** [comment]
@gaborlovasdotcom Make sure this rebases cleanly against master upstream.

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Pull request closed without merging**
