### PR TITLE
LPS-134753 Update JSONUserAPI.macro to handle multiple portals

### PR DESCRIPTION
**Pull request by weller0246**
https://issues.liferay.com/browse/LPS-134753

### CODE REVIEW

**Comment by weller0246** [comment]
ci:test:sf

**Comment by gaborlovasdotcom** [comment]
ci:test:security

**Comment by gaborlovasdotcom** [comment]
ci:test:staging

**Review by gaborlovasdotcom — CHANGES_REQUESTED** [review]
Please change refererence to the JSONUserAPI.macro in the commit message in camelcase format. Thanks.

**Review by gaborlovasdotcom — APPROVED** [review]
LGTM, I alerted other QA leads who use this macro, about his change.

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Comment by pietrobocale** [comment]
ci:test:commerce-functional

**Comment by gaborlovasdotcom** [comment]
ci:test:commerce-functional

**Comment by gaborlovasdotcom** [comment]
ci:test:commerce-functional

**Pull request closed without merging**
