### PR TITLE
LRQA-73362 | master

### PR DESCRIPTION
**Pull request by weller0246**
[LRQA-73362](https://issues.liferay.com/browse/LRQA-73362)

### CODE REVIEW

**Comment by weller0246** [comment]
ci:test:sf

**Comment by weller0246** [comment]
ci:test:staging:nocomiple

**Comment by gaborlovasdotcom** [comment]
ci:test:staging:nocompile

**Review by gaborlovasdotcom — APPROVED** [review]

**Comment by gaborlovasdotcom** [comment]
ci:test:staging:nocompile

**Comment by JoyceWang08211** [comment]
ci:test:staging:nocompile

**Comment by JoyceWang08211** [comment]
Reported the random import issue in https://issues.liferay.com/browse/LPS-149168.

**Review by JoyceWang08211 — APPROVED** [review]
LGTM

**Comment by JoyceWang08211** [comment]
We can forward this PR after remove CI ONLY part.

@weller0246 and @gaborlovasdotcom

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Pull request closed without merging**
