### PR TITLE
LRQA-70353, LRQA-70358, LRQA-70354 | master

### PR DESCRIPTION
**Pull request by Kvale1733**
https://issues.liferay.com/browse/LRQA-70353
https://issues.liferay.com/browse/LRQA-70358
https://issues.liferay.com/browse/LRQA-70354

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
ci:test:security:nocompile

**Review by gaborlovasdotcom — APPROVED** [review]
LGTM, for the FacebookSSO test case, I sent a fix in https://github.com/gaborlovasdotcom/liferay-portal/pull/216

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Pull request closed without merging**
