### PR TITLE
LRQA-72153 | master

### PR DESCRIPTION
**Pull request by gaborlovasdotcom**
[LRQA-72153](https://issues.liferay.com/browse/LRQA-72153)

### CODE REVIEW

**Comment by gaborlovasdotcom** [comment]
ci:test:sf

**Comment by gaborlovasdotcom** [comment]
ci:test:security:nocompile

**Comment by gaborlovasdotcom** [comment]
ci:test:relevant

**Comment by gaborlovasdotcom** [comment]
ci:test:stable

**Review by weller0246 — APPROVED** [review]

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Pull request closed without merging**
