### PR TITLE
LRQA-66196: Add RememberDeviceWithMultipleAuth and RememberDeviceWiMultipleAuthWithoutSession tests

### PR DESCRIPTION
**Pull request by weller0246**
https://issues.liferay.com/browse/LRQA-66196
@gaborlovasdotcom  please take a look at this when you have some time

cc @JoyceWang08211

### CODE REVIEW

**Comment by gaborlovasdotcom** [comment]
ci:test:oauth2:nocompile

**Comment by JoyceWang08211** [comment]
1. Please submit these two testcases separately and update the commit message by following the guidelines below:
```
Group your commits in chunks of logic instead of per line changes.
Include the ticket number in the commit name (see Examples below)
Make the commit names descriptive, starting with a verb. See examples:
“LRQA-54166 Change path from div to ul”
“LRQA-54166 Add macro to navigate away from page”
“LRQA-54166 Create new test for LPS-105474”
```
See details https://qa-compendium.readthedocs.io/en/latest/github/commit-basics.html

**Comment by weller0246** [comment]
@JoyceWang08211  Thanks for the suggestions,  I updated the commits and the test cases based on your comment!

**Comment by gaborlovasdotcom** [comment]
ci:test:sf

**Comment by gaborlovasdotcom** [comment]
ci:test:oauth2:nocompile

**Pull request closed without merging**
