### PR TITLE
LPS-142489 | master

### PR DESCRIPTION
**Pull request by weller0246**
https://issues.liferay.com/browse/LPS-142489

Please review the changes, @gaborlovasdotcom  @ferenconodiD

### CODE REVIEW

**Comment by weller0246** [comment]
ci:test:sf

**Comment by weller0246** [comment]
ci:test:security:nocompile

**Comment by weller0246** [comment]
ci:test:oauth2:nocompile

**Comment by gaborlovasdotcom** [comment]
ci:test:oauth2:nocompile

**Comment by gaborlovasdotcom** [comment]
ci:test:sf

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Pull request closed without merging**
