### PR TITLE
LPS-145951, LPS-145957 | master

### PR DESCRIPTION
**Pull request by JoyceWang08211**
https://issues.liferay.com/browse/LPS-145951
https://issues.liferay.com/browse/LPS-145957

master only, thx

### CODE REVIEW

**Comment by JoyceWang08211** [comment]
ci:test:sf

**Review by gaborlovasdotcom — APPROVED** [review]

**Comment by gaborlovasdotcom** [comment]
ci:test:staging:ncompile

**Comment by gaborlovasdotcom** [comment]
ci:test:staging:nocompile

**Comment by gaborlovasdotcom** [comment]
Related tests are passed.

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Pull request closed without merging**
