### PR TITLE
LRQA-70355, LRQA-70354 | master

### PR DESCRIPTION
**Pull request by Kvale1733**
https://issues.liferay.com/browse/LRQA-70355
https://issues.liferay.com/browse/LRQA-70354

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
ci:test:security:nocompile

**Review by gaborlovasdotcom — APPROVED** [review]
LGTM, OpenIDConnectOnInstanceLevelSmoke has same error as in daily test run

**Comment by gaborlovasdotcom** [comment]
ci:forwrd

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Pull request closed without merging**
