### PR TITLE
LRQA-72513 | master

### PR DESCRIPTION
**Pull request by JoyceWang08211**
https://issues.liferay.com/browse/LRQA-72513

### CODE REVIEW

**Review by gaborlovasdotcom — COMMENTED** [review]
@JoyceWang08211 Could you please define the new test suite to ci.properties file too?

**Comment by gaborlovasdotcom** [comment]
ci:test:sf

**Review by gaborlovasdotcom — CHANGES_REQUESTED** [review]
Could you please fix the formatting error?

**Comment by JoyceWang08211** [comment]
ci:test:sf

**Comment by JoyceWang08211** [comment]
ci:test:oidc:nocompile

**Comment by JoyceWang08211** [comment]
ci:test:sf

**Comment by JoyceWang08211** [comment]
ci:test:sf

**Comment by JoyceWang08211** [comment]
ci:test:oidc:nocompile

**Comment by JoyceWang08211** [comment]
Reported the Jenkins issue in [LRCI-2726](https://issues.liferay.com/browse/LRCI-2726).

**Comment by JoyceWang08211** [comment]
I closed LRCI-2726 as discared as we cannot trigger the new added test suite until it merge to portal.

**Review by gaborlovasdotcom — APPROVED** [review]

**Comment by gaborlovasdotcom** [comment]
ci:test:sf

**Comment by gaborlovasdotcom** [comment]
ci:test:ldap:nocompile

**Comment by gaborlovasdotcom** [comment]
ci:test:mfa:nocompile

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Pull request closed without merging**
