### PR TITLE
LPS-142980 | master

### PR DESCRIPTION
**Pull request by 91nilo**
https://issues.liferay.com/browse/LPS-142980

### CODE REVIEW

**Comment by 91nilo** [comment]
ci:test:sf

**Comment by 91nilo** [comment]
ci:test:security

**Comment by 91nilo** [comment]
@gaborlovasdotcom I also tried to apply the GWT to the tasks, could you please check that too along with the fix and tell me if there's something needing changes?
Thanks!

**Review by gaborlovasdotcom — COMMENTED** [review]
Task names are looking good to me

**Review by JoyceWang08211 — COMMENTED** [review]
Task names look good to me, but testcase doesn't pass on Jenkins with current modification:
https://testray.liferay.com/home/-/testray/case_results/1647065585

Need to additional fix. @91nilo 

cc @gaborlovasdotcom

**Comment by weller0246** [comment]
Please create a different ticket for this PR as long as you only rebase the description and task and not fix the test error, thank you

**Comment by weller0246** [comment]
Please create a different ticket for this PR as long as you only rebase the description and task and not fix the test error, thank you

**Comment by 91nilo** [comment]
I've created a new PR using only the tasks:
[#359](https://github.com/gaborlovasdotcom/liferay-portal/pull/359)
cc: @gaborlovasdotcom, @weller0246, @JoyceWang08211

**Pull request closed without merging**
