### PR TITLE
LRQA-71092 | master

### PR DESCRIPTION
**Pull request by weller0246**
https://issues.liferay.com/browse/LRQA-71092

### CODE REVIEW

**Comment by weller0246** [comment]
ci:test:staging:nocompile

**Review by gaborlovasdotcom — COMMENTED** [review]
What is the maximum timeout of WaitForElementPresent?

**Comment by JoyceWang08211** [comment]
> @weller0246, What is the maximum timeout of WaitForElementPresent?

Based on [Line 3210](https://github.com/liferay/liferay-portal/blob/master/modules/test/poshi/poshi-runner/src/main/java/com/liferay/poshi/runner/selenium/BaseWebDriverImpl.java#L3210) and [Line 4504](https://github.com/liferay/liferay-portal/blob/master/modules/test/poshi/poshi-runner/src/main/java/com/liferay/poshi/runner/selenium/BaseWebDriverImpl.java#L4504) in BaseWebDriverImpl.java, the maximum timeout of WaitForElementPresent should be 60 seconds.(timeout.explicit.wait=60)

**Comment by JoyceWang08211** [comment]
LGTM

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Pull request closed without merging**
