### PR TITLE
LRQA-72013, LRQA-72009, LRQA-72010 | master

### PR DESCRIPTION
**Pull request by Kvale1733**
https://issues.liferay.com/browse/LRQA-72013
https://issues.liferay.com/browse/LRQA-72009
https://issues.liferay.com/browse/LRQA-72010

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
ci:test:OpenIDConnect:nocompile

**Comment by Kvale1733** [comment]
ci:test:security:nocompile

**Review by gaborlovasdotcom — APPROVED** [review]

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Pull request closed without merging**
