### PR TITLE
LPS-133095 Adding new SAML test cases

### PR DESCRIPTION
**Pull request by ferenconodiD**
[LPS-133095](https://issues.liferay.com/browse/LPS-133095)

### CODE REVIEW

**Comment by ferenconodiD** [comment]
ci:test:sf

**Comment by ferenconodiD** [comment]
ci:test:security:nocompile

**Review by gaborlovasdotcom — APPROVED** [review]
LGTM!

**Review by gaborlovasdotcom — APPROVED** [review]

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Pull request closed without merging**
