### PR TITLE
LRQA-73295

### PR DESCRIPTION
**Pull request by weller0246**
https://issues.liferay.com/browse/LRQA-73295

### CODE REVIEW

**Comment by weller0246** [comment]
ci:test:sf

**Comment by weller0246** [comment]
ci:test:staging

**Comment by gaborlovasdotcom** [comment]
ci:stop

**Comment by gaborlovasdotcom** [comment]
@weller0246 , could you please check the SF issue?

**Comment by JoyceWang08211** [comment]
A little confused about the current PR and https://github.com/weller0246/liferay-portal/pull/23. Should we close one of them or actually they are different behaviors? @weller0246 

cc @gaborlovasdotcom

**Comment by weller0246** [comment]
Hy! 
I wanted to close this issue, sorry for the inconvenience with this duplicate!

**Pull request closed without merging**
