### PR TITLE
LRQA-77989 | master

### PR DESCRIPTION
**Pull request by gaborlovasdotcom**
[LRQA-77989](https://issues.liferay.com/browse/LRQA-77989)

### CODE REVIEW

**Comment by gaborlovasdotcom** [comment]
ci:test:sf

**Comment by gaborlovasdotcom** [comment]
ci:test:security:nocompile

**Review by JoyceWang08211 — APPROVED** [review]
LGTM

**Comment by gaborlovasdotcom** [comment]
ci:test:security:nocompile

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Pull request closed without merging**
