### PR TITLE
LPS-132630 Update OAuth2.testcase to work with UI login

### PR DESCRIPTION
**Pull request by weller0246**
https://issues.liferay.com/browse/LPS-132630

### CODE REVIEW

**Comment by weller0246** [comment]
ci:test:sf

**Comment by weller0246** [comment]
ci:test:sf

**Comment by gaborlovasdotcom** [comment]
ci:test:oauth2:nocompile

**Comment by gaborlovasdotcom** [comment]
Discarded, see my comments in: https://issues.liferay.com/browse/LPS-132630

**Pull request closed without merging**
