### PR TITLE
LPS-136402  Fix url in ViewIdPSingleLogoutWithMultipleSPs test

### PR DESCRIPTION
**Pull request by weller0246**
https://issues.liferay.com/browse/LPS-136402

### CODE REVIEW

**Comment by weller0246** [comment]
ci:test:saml:nocompile

**Comment by weller0246** [comment]
ci:test:sf

**Comment by weller0246** [comment]
cc @gaborlovasdotcom  please review and close the pr if you have the time

**Comment by weller0246** [comment]
ci:test:saml:nocompile

**Comment by weller0246** [comment]
ci:test:saml:nocompile

**Review by gaborlovasdotcom — APPROVED** [review]

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Pull request closed without merging**
