### PR TITLE
LRQA-72140 | master

### PR DESCRIPTION
**Pull request by weller0246**
https://issues.liferay.com/browse/LRQA-72140

### CODE REVIEW

**Comment by weller0246** [comment]
ci:test:security:nocompile

**Review by gaborlovasdotcom — CHANGES_REQUESTED** [review]
Please replace the commit message's ticket ID.

**Comment by gaborlovasdotcom** [comment]
ci:test:sf

**Review by gaborlovasdotcom — APPROVED** [review]

**Comment by gaborlovasdotcom** [comment]
ci:test:sf

**Comment by gaborlovasdotcom** [comment]
ci:test:security:nocompile

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Pull request closed without merging**
