### PR TITLE
LRQA-70557 | AntiSamy.testcase | SACRED update: Apply task groups on test steps

### PR DESCRIPTION
**Pull request by LucasAcacio**
https://issues.liferay.com/browse/LRQA-70557

### CODE REVIEW

**Comment by LucasAcacio** [comment]
ci:test:sf

**Comment by LucasAcacio** [comment]
ci:test:security

**Review by gaborlovasdotcom — APPROVED** [review]
LGTM!

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Pull request closed without merging**
