### PR TITLE
LRQA-84469 | master

### PR DESCRIPTION
**Pull request by gaborlovasdotcom**
[LRQA-84469](https://liferay.atlassian.net/browse/LRQA-84469)

### CODE REVIEW

**Comment by gaborlovasdotcom** [comment]
ci:test:oauth2:nocompile

**Comment by gaborlovasdotcom** [comment]
ci:stop

**Comment by gaborlovasdotcom** [comment]
ci:test:sf

**Comment by gaborlovasdotcom** [comment]
ci:test:oauth2:nocompile

**Comment by gaborlovasdotcom** [comment]
ci:test:oauth2:nocompile

**Comment by gaborlovasdotcom** [comment]
ci:test:oauth2:nocompile

**Comment by gaborlovasdotcom** [comment]
ci:test:saml:nocompile

**Comment by gaborlovasdotcom** [comment]
ci:test:sf

**Comment by gaborlovasdotcom** [comment]
ci:test:oauth2:nocompile

**Comment by gaborlovasdotcom** [comment]
ci:stop

**Comment by gaborlovasdotcom** [comment]
ci:test:oauth2:nocompile

**Comment by gaborlovasdotcom** [comment]
ci:test:oauth2:nocompile

**Comment by gaborlovasdotcom** [comment]
ci:test:sf

**Comment by gaborlovasdotcom** [comment]
ci:test:relevant

**Comment by gaborlovasdotcom** [comment]
ci:test:sf

**Comment by gaborlovasdotcom** [comment]
ci:test:relevant

**Comment by gaborlovasdotcom** [comment]
ci:test:sf

**Comment by gaborlovasdotcom** [comment]
ci:test:relevant

**Comment by gaborlovasdotcom** [comment]
ci:test:oidc:nocompile

**Comment by gaborlovasdotcom** [comment]
ci:test:oauth2:nocompile

**Comment by gaborlovasdotcom** [comment]
ci:test:saml:nocompile

**Comment by gaborlovasdotcom** [comment]
ci:forward:force

**Comment by gaborlovasdotcom** [comment]
Forwarded manually in: https://github.com/brianchandotcom/liferay-portal/pull/144131

**Comment by gaborlovasdotcom** [comment]
ci:test:saml:nocompile

**Comment by gaborlovasdotcom** [comment]
ci:test:oauth2:nocompile

**Comment by gaborlovasdotcom** [comment]
ci:test:cookies:nocompile

**Comment by gaborlovasdotcom** [comment]
ci:test:oauth2:nocompile

**Comment by gaborlovasdotcom** [comment]
ci stop

**Comment by gaborlovasdotcom** [comment]
ci:stop

**Comment by gaborlovasdotcom** [comment]
ci:test:oauth2:nocompile

**Comment by gaborlovasdotcom** [comment]
ci:test:cookies:nocompile

**Comment by gaborlovasdotcom** [comment]
ci:test:saml:nocompile

**Comment by JoyceWang08211** [comment]
Continued in https://github.com/liferay-appsec/liferay-portal/pull/1525

**Comment by JoyceWang08211** [comment]
> ### ❌ ci:test:saml - 84 out of 92 jobs passed in 1 hour 40 minutes
> Click here for more details.

There is no companyId parameter in com.liferay.portal.remote.cors.configuration.PortalCORSConfiguration~allow~headless~admin~user.config. 
So the replace action will not execute:
`<replace
			file="${liferay.home}/${osgi.config.file.name}"
			token="companyId=L&quot;20098&quot;"
			value="companyId=L&quot;${companyId}&quot;"
		/>`
That's the reason why config file doesn't work on www.able.com:9080 instance.

**Comment by gaborlovasdotcom** [comment]
ci:test:saml:nocompile

**Comment by gaborlovasdotcom** [comment]
ci:test:oauth2:nocompile

**Comment by gaborlovasdotcom** [comment]
ci:test:sf

**Comment by gaborlovasdotcom** [comment]
ci:test:oauth2:nocompile

**Comment by gaborlovasdotcom** [comment]
ci:test:sf

**Comment by gaborlovasdotcom** [comment]
ci:test:oauth2:nocompile

**Comment by gaborlovasdotcom** [comment]
ci:test:saml:nocopile

**Comment by gaborlovasdotcom** [comment]
ci:test:cookies:nocompile

**Comment by gaborlovasdotcom** [comment]
ci:test:cookies:nocompile

**Comment by gaborlovasdotcom** [comment]
ci:test:saml:nocompile

**Comment by gaborlovasdotcom** [comment]
ci:test:saml:nocompile

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Comment by gaborlovasdotcom** [comment]
ci:stop

**Comment by gaborlovasdotcom** [comment]
ci:forward:force

**Comment by gaborlovasdotcom** [comment]
Forwarded directly in https://github.com/brianchandotcom/liferay-portal/pull/144233

**Comment by gaborlovasdotcom** [comment]
ci:close

**Pull request closed without merging**
