### PR TITLE
LRQA-70438 | master

### PR DESCRIPTION
**Pull request by Kvale1733**
https://issues.liferay.com/browse/LRQA-70438

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
ci:test:security:nocompile

**Review by gaborlovasdotcom — COMMENTED** [review]
Hi @Kvale1733 ,
Compared to [recent daily run](https://testray.liferay.com/home/-/testray/case_results/index?p_p_state=normal&orderByCol=status_sortable&orderByType=asc&testrayBuildId=1582857734&testrayComponentId=1310779464&statuses=3) this change has additional 4 new failing test case:

1. SAML#AssertSSOFailsWhenAlgorithmsMismatch
2. SAML#AssertSSOWithEncryptionAndDecryption
3. SAML#SPInitiatedSSOWithScreenNameIdentifier
4. SAML#ViewSingleLogoutHTTPPostBindingInConsole

Could you please check if it's related to this PR?

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
ci:test:security:nocompile

**Comment by weller0246** [comment]
The changes look good to me, great work! Resolve the remaining conflict and it is all good from my side

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
ci:test:saml:nocompile

**Comment by gaborlovasdotcom** [comment]
ci:test:saml:nocompile

**Review by gaborlovasdotcom — COMMENTED** [review]
Hi @Kvale1733 could you please rebase on master?

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
ci:test:saml:nocompile

**Comment by Kvale1733** [comment]
@gaborlovasdotcom Hey Gabor. The current 4 failures for SAML on my PR are recurring failures not related to my changes. I am ready for review again.

**Review by gaborlovasdotcom — APPROVED** [review]
LGTM!

**Comment by gaborlovasdotcom** [comment]
Continued in https://github.com/gaborlovasdotcom/liferay-portal/pull/249, due to conflict

**Pull request closed without merging**
