### PR TITLE
LPS-146741 | master

### PR DESCRIPTION
**Pull request by JoyceWang08211**
https://issues.liferay.com/browse/LPS-146741

master only, thx

### CODE REVIEW

**Comment by JoyceWang08211** [comment]
See details in https://github.com/JoyceWang08211/liferay-portal/pull/36

**Comment by JoyceWang08211** [comment]
ci:test:sf

**Comment by JoyceWang08211** [comment]
ci:test:sf

**Comment by JoyceWang08211** [comment]
I will rebase and resolved conflict after https://github.com/gaborlovasdotcom/liferay-portal/pull/309 sync to master.

**Review by gaborlovasdotcom — APPROVED** [review]
LGTM

**Pull request closed without merging**
