### PR TITLE
LRQA-70573 | GoogleSSO.testcase | SACRED update: Apply task groups on test steps 

### PR DESCRIPTION
**Pull request by LucasAcacio**
https://issues.liferay.com/browse/LRQA-70573

### CODE REVIEW

**Comment by LucasAcacio** [comment]
ci:test:sf

**Comment by LucasAcacio** [comment]
ci:test:security

**Review by gaborlovasdotcom — CHANGES_REQUESTED** [review]
Please update the Commit ID to LRQA-70573

**Review by gaborlovasdotcom — APPROVED** [review]
LGTM!

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Pull request closed without merging**
