### PR TITLE
LRQA-70500 | master

### PR DESCRIPTION
**Pull request by Kvale1733**
https://issues.liferay.com/browse/LRQA-70500

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:sf

**Review by weller0246 — APPROVED** [review]

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
@gaborlovasdotcom test case names have been changed, ready for review

**Review by gaborlovasdotcom — APPROVED** [review]

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Pull request closed without merging**
