### PR TITLE
LRQA-71111 Extending description

### PR DESCRIPTION
**Pull request by weller0246**
https://issues.liferay.com/browse/LRQA-71111

### CODE REVIEW

**Comment by JoyceWang08211** [comment]
LGTM

**Comment by JoyceWang08211** [comment]
ci:test:sf

**Review by JoyceWang08211 — APPROVED** [review]

**Review by gaborlovasdotcom — APPROVED** [review]

**Review by ferenconodiD — APPROVED** [review]
LGTM!

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Pull request closed without merging**
