### PR TITLE
 LPS-133093 Adding tests for CI test

### PR DESCRIPTION
**Pull request by weller0246**
https://issues.liferay.com/browse/LPS-133093

### CODE REVIEW

**Comment by weller0246** [comment]
ci:test:sf

**Review by gaborlovasdotcom — CHANGES_REQUESTED** [review]
Please, apply local source format runs, and update the code, else the source code format validator job will fail.

**Comment by weller0246** [comment]
Thanks for the heads up, somehow one of the formatting commands did not run before pushing to github.

**Comment by weller0246** [comment]
ci:test:sf

**Pull request closed without merging**
