### PR TITLE
LRQA-70466 | master

### PR DESCRIPTION
**Pull request by Kvale1733**
https://issues.liferay.com/browse/LRQA-70466

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
ci:test:security:nocompile

**Review by gaborlovasdotcom — APPROVED** [review]
LGTM, same errors are present at [test run](https://testray.liferay.com/home/-/testray/case_results/index?p_p_state=normal&orderByCol=status_sortable&orderByType=asc&testrayBuildId=1580234388&testrayComponentId=1310725251&testrayRunId=1580234423).
RCAs are kicked off for the 2 failing tests.

**Review by ferenconodiD — APPROVED** [review]
LGTM!

**Review by weller0246 — APPROVED** [review]

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Pull request closed without merging**
