### PR TITLE
LRQA-70386 | master

### PR DESCRIPTION
**Pull request by Kvale1733**
https://issues.liferay.com/browse/LRQA-70386

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
ci:test:security:nocompile

**Review by gaborlovasdotcom — APPROVED** [review]

**Comment by gaborlovasdotcom** [comment]
[NTLM tests are passed](https://testray.liferay.com/home/-/testray/case_results?tab=runs&testrayBuildId=1578055196)

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Pull request closed without merging**
